// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vWtvcLFhqbJHykYDMVr5KamZK9VNAQs',
    appId: '1:362523315872:web:3641995df73f10dde983c5',
    messagingSenderId: '362523315872',
    projectId: 'feedback-expo-2025',
    authDomain: 'feedback-expo-2025.firebaseapp.com',
    storageBucket: 'feedback-expo-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAioYhwqhafjCJt5saJnlcCYmL_ijjzo2o',
    appId: '1:362523315872:android:a3374ca3b4219eb6e983c5',
    messagingSenderId: '362523315872',
    projectId: 'feedback-expo-2025',
    storageBucket: 'feedback-expo-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrsVNUdHQ62QCHutsntkhcTHpsBorUtKo',
    appId: '1:362523315872:ios:9901dfad3d47d372e983c5',
    messagingSenderId: '362523315872',
    projectId: 'feedback-expo-2025',
    storageBucket: 'feedback-expo-2025.firebasestorage.app',
    iosBundleId: 'com.example.feedbackFormExpo25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrsVNUdHQ62QCHutsntkhcTHpsBorUtKo',
    appId: '1:362523315872:ios:9901dfad3d47d372e983c5',
    messagingSenderId: '362523315872',
    projectId: 'feedback-expo-2025',
    storageBucket: 'feedback-expo-2025.firebasestorage.app',
    iosBundleId: 'com.example.feedbackFormExpo25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1vWtvcLFhqbJHykYDMVr5KamZK9VNAQs',
    appId: '1:362523315872:web:f3bcd178850659dbe983c5',
    messagingSenderId: '362523315872',
    projectId: 'feedback-expo-2025',
    authDomain: 'feedback-expo-2025.firebaseapp.com',
    storageBucket: 'feedback-expo-2025.firebasestorage.app',
  );

}